builders:
  matchito:
    import: "package:matchito/builder.dart"
    builder_factories: ["matchito"]
    build_extensions: { ".dart": [".matchers.dart"] }
    auto_apply: dependents
    build_to: source