name: matchito_annotation
description: >
  Annotations for the matchito code-generator.
  This package does nothing without matchito.
version: 0.0.1
repository: https://github.com/jtdLab/matchito
issue_tracker: https://github.com/jtdLab/matchito/issues

environment:
  sdk: ^3.7.0

dev_dependencies:
  test: ^1.25.15
